# This is a basic workflow to help you get started with Actions

name: CI-CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
      
      #Fazer Login no Docker Hub
      - name: Docker Login
        uses: docker/login-action@v1.14.1
        with:
         #Nome e senha (Armazenados no Secret)
         username: ${{ secrets.DOCKERHUB_USER}}
         password: ${{ secrets.DOCKERHUB_PWD}}
     
     # Fazer o Build e o Push da Imagem
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.10.0
        with:
          context: ./src
          #Onde esta o arquivo dockerfile
          file: ./src/Dockerfile
          push: true
          #Imagem com a tag deversão para fazer a build e subir pro docker hub
          tags: |
            felipevarejao/conversao-temperatura:latest
            felipevarejao/conversao-temperatura:v${{ github.run_number }}
